/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_xcp_neihan_utils_PatchUtil */

#ifndef _Included_com_xcp_neihan_utils_PatchUtil
#define _Included_com_xcp_neihan_utils_PatchUtil
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_xcp_neihan_utils_PatchUtil
 * Method:    combine
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_xcp_neihan_utils_PatchUtil_combine
        (JNIEnv *, jclass, jstring, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
