/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_xcp_neihan_utils_ImageUtil */

#ifndef _Included_com_xcp_neihan_utils_ImageUtil
#define _Included_com_xcp_neihan_utils_ImageUtil
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_xcp_neihan_utils_ImageUtil
 * Method:    compressBitmap
 * Signature: (Landroid/graphics/Bitmap;ILjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_xcp_neihan_utils_ImageUtil_compressBitmap
  (JNIEnv *, jclass, jobject, jint, jstring);

/*
 * Class:     com_xcp_neihan_utils_ImageUtil
 * Method:    getMessage
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_xcp_neihan_utils_ImageUtil_getMessage
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
