/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_xcp_neihan_MainActivity */

#ifndef _Included_com_xcp_neihan_MainActivity
#define _Included_com_xcp_neihan_MainActivity
#ifdef __cplusplus
extern "C" {
#endif
#undef com_xcp_neihan_MainActivity_STORAGE_REQUEST
#define com_xcp_neihan_MainActivity_STORAGE_REQUEST 1L
/*
 * Class:     com_xcp_neihan_MainActivity
 * Method:    sayHello
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_xcp_neihan_MainActivity_sayHello
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
